In [ ]:
# read npy file
import numpy as np

# load the data
indices = np.load('knn_indices.npy')
points = np.load('points.npy')
timestamps = np.load('timestamps.npy')

print("KNN Indices shape:", indices.shape)
print("Points shape:", points.shape)
print("Timestamps shape:", timestamps.shape)


KNN Indices shape: (508, 512, 6)
Points shape: (508, 512, 3)
Timestamps shape: (508,)


In [3]:
indices

array([[[ 45,  57,  63,   4,  26,  56],
        [ 46,  44,  36,   3,  47,   7],
        [ 31,  54,  15,  24,  48,   4],
        ...,
        [489, 368, 363, 325, 269, 499],
        [501, 487, 505, 504, 496, 497],
        [363, 493, 503, 506, 368, 488]],

       [[ 45,  57,  63,   4,  26,  56],
        [ 46,  44,  36,   3,  47,   7],
        [ 31,  54,  15,  24,  48,   4],
        ...,
        [489, 368, 363, 325, 499, 269],
        [501, 487, 505, 504, 496, 497],
        [368, 363, 493, 503, 506, 488]],

       [[ 45,  57,  63,   4,  26,  56],
        [ 46,  44,  36,   3,  47,   7],
        [ 31,  54,  15,  24,  48,   4],
        ...,
        [489, 368, 363, 325, 499, 495],
        [501, 487, 505, 504, 496, 497],
        [368, 493, 503, 506, 363, 488]],

       ...,

       [[ 45,  57,  63,   4,  26,  56],
        [ 46,  44,  36,   3,  47,   7],
        [ 31,  54,  15,  24,  48,   4],
        ...,
        [489, 347, 391, 499, 495, 511],
        [501, 487, 505, 504, 496, 497],
        [

In [4]:
points

array([[[-2.69827992e-02,  1.76851943e-01,  7.78904036e-02],
        [ 4.79497872e-02,  9.43128616e-02, -1.42817050e-01],
        [-9.93122682e-02,  1.47701368e-01, -1.50092132e-02],
        ...,
        [-4.38445687e-01,  6.74666405e-01, -1.46303512e-02],
        [-5.15115738e-01,  6.09547079e-01, -1.15065193e-02],
        [-4.35270220e-01,  6.52812302e-01, -4.76704538e-02]],

       [[-2.47823112e-02,  1.76851943e-01,  7.86182135e-02],
        [ 4.39156555e-02,  9.43128616e-02, -1.44108668e-01],
        [-9.96949822e-02,  1.47701368e-01, -1.22111998e-02],
        ...,
        [-4.47272807e-01,  6.63570166e-01, -4.06442850e-04],
        [-5.22399366e-01,  5.96984863e-01,  6.73379842e-03],
        [-4.43394274e-01,  6.39649928e-01, -3.19042653e-02]],

       [[-2.25991681e-02,  1.76851943e-01,  7.92733505e-02],
        [ 3.99144888e-02,  9.43128616e-02, -1.45267770e-01],
        [-9.99944881e-02,  1.47701368e-01, -9.45012365e-03],
        ...,
        [-4.55756843e-01,  6.53392136e-01,

In [5]:
timestamps

array([ 0.025 ,  0.0625,  0.0994,  0.1366,  0.1727,  0.2086,  0.245 ,
        0.2818,  0.3185,  0.3542,  0.3898,  0.4258,  0.4616,  0.497 ,
        0.5324,  0.568 ,  0.6031,  0.6388,  0.6745,  0.7099,  0.7456,
        0.7809,  0.8164,  0.8514,  0.8866,  0.9218,  0.9566,  0.9912,
        1.0255,  1.0595,  1.093 ,  1.1269,  1.1602,  1.194 ,  1.2277,
        1.2613,  1.2948,  1.3289,  1.3625,  1.3963,  1.4367,  1.4706,
        1.5043,  1.5396,  1.5738,  1.6075,  1.6411,  1.6744,  1.708 ,
        1.7415,  1.7753,  1.8089,  1.8421,  1.8756,  1.9086,  1.9422,
        1.9756,  2.0089,  2.0422,  2.0753,  2.1084,  2.1414,  2.1748,
        2.2083,  2.2416,  2.2747,  2.3075,  2.3406,  2.3737,  2.4069,
        2.4399,  2.473 ,  2.5062,  2.5393,  2.5728,  2.6063,  2.6401,
        2.6738,  2.7078,  2.7414,  2.7755,  2.809 ,  2.8428,  2.8769,
        2.9109,  2.9446,  2.979 ,  3.013 ,  3.0471,  3.0811,  3.1148,
        3.1484,  3.1822,  3.2155,  3.249 ,  3.2824,  3.3155,  3.3492,
        3.3829,  3.4